[package]
name = "ClipGrammarPedant"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }

